packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': set this to true or false
  "@prisma/engines@7.9.1": true
  "esbuild@0.28.2": true
  "prisma@7.9.1": true
  unrs-resolver: true
