export const AUDIT_ACTIONS = {
  COMPANY_CREATED: 'company.created',
  COMPANY_UPDATED: 'company.updated',
  COMPANY_STATUS_CHANGED: 'company.status_changed',
  COMPANY_DELETED: 'company.deleted',
  COMPANY_CONTACT_UPDATED: 'company.contact.updated',
  COMPANY_PROFILE_UPDATED: 'company.profile.updated',
  COMPANY_LOGO_UPDATED: 'company.logo.updated',
  COMPANY_IDENTITY_CHANGE_REQUESTED: 'company.identity_change.requested',
  COMPANY_IDENTITY_CHANGE_REVIEWED: 'company.identity_change.reviewed',

  USER_INVITED: 'user.invited',
  USER_STATUS_CHANGED: 'user.status_changed',
  USER_ARCHIVED: 'user.archived',
  USER_DELETED: 'user.deleted',
  USER_ROLES_CHANGED: 'user.roles_changed',
  USER_PROFILE_UPDATED: 'user.profile.updated',
  USER_AVATAR_UPDATED: 'user.avatar.updated',

  ROLE_CREATED: 'role.created',
  ROLE_UPDATED: 'role.updated',
  ROLE_DELETED: 'role.deleted',
  ROLE_ARCHIVED: 'role.archived',
  ROLE_RESTORED: 'role.restored',
  SERVICE_DELETED: 'service.deleted',
  SERVICE_FEATURE_DEFINITION_DELETED: 'service.feature_definition.deleted',
  TRAINING_CATEGORY_DELETED: 'training.category.deleted',
  TRAINING_COURSE_DELETED: 'training.course.deleted',

  AUTH_INVITATION_ACCEPTED: 'auth.invitation.accepted',

  SERVICE_BATCH_STATUS_CHANGED: 'service.batch_status_changed',
  SERVICE_FEATURE_CREATED: 'service.feature.created',
  SERVICE_FEATURE_DEFINITION_CREATED: 'service.feature_definition.created',
  SERVICE_FEATURE_DEFINITION_UPDATED: 'service.feature_definition.updated',
  SERVICE_FEATURE_DEFINITION_ATTACHED: 'service.feature_definition.attached',
  SERVICE_FEATURE_UPDATED: 'service.feature.updated',
  SERVICE_FEATURE_REORDERED: 'service.feature.reordered',
  SERVICE_ASSIGNMENT_FEATURE_UPDATED: 'service.assignment.feature.updated',
  SERVICE_ASSIGNMENT_FEATURES_SYNCED: 'service.assignment.features_synced',
  SERVICE_ASSIGNMENT_STATUS_TRANSITIONED:
    'service.assignment.status_transitioned',
  SERVICE_ASSIGNMENT_BATCH_TRANSITIONED:
    'service.assignment.batch_transitioned',

  SUBSCRIPTION_CREATED: 'subscription.created',
  SUBSCRIPTION_UPDATED: 'subscription.updated',
  SUBSCRIPTION_RENEWED: 'subscription.renewed',
  SUBSCRIPTION_CANCELLED: 'subscription.cancelled',
  SUBSCRIPTION_RENEWAL_REQUESTED: 'subscription.renewal.requested',
  SUBSCRIPTION_RENEWAL_APPROVED: 'subscription.renewal.approved',
  SUBSCRIPTION_RENEWAL_REJECTED: 'subscription.renewal.rejected',
  FILE_UPLOADED: 'file.uploaded',
  FILE_DELETED: 'file.deleted',

  TRAINING_CATEGORY_CREATED: 'training.category.created',
  TRAINING_CATEGORY_UPDATED: 'training.category.updated',
  TRAINING_CATEGORY_BATCH_STATUS_CHANGED:
    'training.category.batch_status_changed',
  TRAINING_COURSE_CREATED: 'training.course.created',
  TRAINING_COURSE_UPDATED: 'training.course.updated',
  TRAINING_COURSE_STRUCTURE_UPDATED: 'training.course.structure.updated',
  TRAINING_COURSE_BATCH_STATUS_CHANGED: 'training.course.batch_status_changed',
  TRAINING_SECTION_CREATED: 'training.section.created',
  TRAINING_SECTION_UPDATED: 'training.section.updated',
  TRAINING_SECTION_DELETED: 'training.section.deleted',
  TRAINING_LESSON_CREATED: 'training.lesson.created',
  TRAINING_LESSON_UPDATED: 'training.lesson.updated',
  TRAINING_LESSON_DELETED: 'training.lesson.deleted',
  TRAINING_VIDEO_UPLOAD_CREATED: 'training.video_upload.created',
  TRAINING_VIDEO_ASSET_UPDATED: 'training.video_asset.updated',
  TRAINING_ACCESS_ASSIGNED: 'training.access.assigned',
  TRAINING_ACCESS_REVOKED: 'training.access.revoked',
  TRAINING_QUIZ_CREATED: 'training.quiz.created',
  TRAINING_QUIZ_UPDATED: 'training.quiz.updated',
  TRAINING_COURSE_COMPLETED: 'training.course.completed',
  TRAINING_CERTIFICATE_TEMPLATE_CREATED:
    'training.certificate_template.created',
  TRAINING_CERTIFICATE_TEMPLATE_UPDATED:
    'training.certificate_template.updated',
  TRAINING_CERTIFICATE_ISSUED: 'training.certificate.issued',
  TRAINING_CERTIFICATE_REVOKED: 'training.certificate.revoked',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
