export type SettingCategory =
  | 'general'
  | 'theme'
  | 'companies'
  | 'notifications'
  | 'helpdesk'
  | 'trainings'
  | 'files';

export type SettingValueType = 'STRING' | 'NUMBER' | 'BOOLEAN' | 'SECRET';
export type SettingPrimitive = string | number | boolean;

export interface SettingDefinition {
  key: string;
  category: SettingCategory;
  valueType: SettingValueType;
  defaultValue: SettingPrimitive;
  companyVisible: boolean;
  companyOverridable: boolean;
  companyWritable: boolean;
  allowEmpty?: boolean;
  maxLength?: number;
  min?: number;
  max?: number;
  allowedValues?: readonly SettingPrimitive[];
}

export const SETTINGS_REGISTRY: readonly SettingDefinition[] = [
  {
    key: 'general.site_title',
    category: 'general',
    valueType: 'STRING',
    defaultValue: 'OdooKRD',
    companyVisible: true,
    companyOverridable: false,
    companyWritable: false,
    allowEmpty: false,
    maxLength: 150,
  },
  {
    key: 'general.default_locale',
    category: 'general',
    valueType: 'STRING',
    defaultValue: 'ku',
    companyVisible: true,
    companyOverridable: true,
    companyWritable: true,
    allowedValues: ['ku', 'ar', 'en'],
  },
  {
    key: 'general.timezone',
    category: 'general',
    valueType: 'STRING',
    defaultValue: 'Asia/Baghdad',
    companyVisible: true,
    companyOverridable: true,
    companyWritable: true,
    allowEmpty: false,
    maxLength: 100,
  },
  {
    key: 'theme.default_font',
    category: 'theme',
    valueType: 'STRING',
    defaultValue: 'Noto Kufi Arabic',
    companyVisible: true,
    companyOverridable: true,
    companyWritable: true,
    allowEmpty: false,
    maxLength: 150,
    allowedValues: [
      'Noto Kufi Arabic',
      'Noto Sans Arabic',
      'Arial',
      'system-ui',
    ],
  },
  {
    key: 'companies.max_users_per_company',
    category: 'companies',
    valueType: 'NUMBER',
    defaultValue: 25,
    companyVisible: true,
    companyOverridable: true,
    companyWritable: false,
    min: 1,
    max: 100000,
  },
  {
    key: 'notifications.in_app.enabled',
    category: 'notifications',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: true,
    companyOverridable: true,
    companyWritable: true,
  },
  {
    key: 'notifications.email.enabled',
    category: 'notifications',
    valueType: 'BOOLEAN',
    defaultValue: false,
    companyVisible: true,
    companyOverridable: true,
    companyWritable: true,
  },
  {
    key: 'notifications.email.provider',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: 'amazon_ses',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['amazon_ses'],
  },
  {
    key: 'notifications.email.amazon_ses.region',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 50,
  },

  {
    key: 'notifications.email.amazon_ses.transport',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: 'api',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['api', 'smtp'],
  },
  {
    key: 'notifications.email.amazon_ses.smtp_port',
    category: 'notifications',
    valueType: 'NUMBER',
    defaultValue: 587,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 1,
    max: 65535,
  },
  {
    key: 'notifications.email.amazon_ses.smtp_security',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: 'starttls',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['starttls', 'tls'],
  },
  {
    key: 'notifications.email.amazon_ses.smtp_username',
    category: 'notifications',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 256,
  },
  {
    key: 'notifications.email.amazon_ses.smtp_password',
    category: 'notifications',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 1024,
  },
  {
    key: 'notifications.email.amazon_ses.access_key_id',
    category: 'notifications',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 256,
  },
  {
    key: 'notifications.email.amazon_ses.secret_access_key',
    category: 'notifications',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 1024,
  },
  {
    key: 'notifications.email.amazon_ses.session_token',
    category: 'notifications',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 8192,
  },
  {
    key: 'notifications.email.sender_email',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 320,
  },
  {
    key: 'notifications.email.sender_name',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: 'OdooKRD',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 150,
  },
  {
    key: 'notifications.email.reply_to',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 320,
  },
  {
    key: 'notifications.whatsapp.enabled',
    category: 'notifications',
    valueType: 'BOOLEAN',
    defaultValue: false,
    companyVisible: true,
    companyOverridable: true,
    companyWritable: true,
  },
  {
    key: 'notifications.whatsapp.api_url',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 2048,
  },
  {
    key: 'notifications.whatsapp.phone_number_id',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 150,
  },
  {
    key: 'notifications.whatsapp.business_account_id',
    category: 'notifications',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 150,
  },
  {
    key: 'notifications.whatsapp.access_token',
    category: 'notifications',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 8192,
  },
  {
    key: 'notifications.whatsapp.webhook_verify_token',
    category: 'notifications',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 1024,
  },
  {
    key: 'files.storage.default_provider',
    category: 'files',
    valueType: 'STRING',
    defaultValue: 'LOCAL',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['LOCAL', 'AWS_S3'],
  },
  {
    key: 'files.upload.max_image_mb',
    category: 'files',
    valueType: 'NUMBER',
    defaultValue: 10,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 1,
    max: 100,
  },
  {
    key: 'files.upload.max_document_mb',
    category: 'files',
    valueType: 'NUMBER',
    defaultValue: 50,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 1,
    max: 100,
  },
  {
    key: 'files.upload.max_attachment_mb',
    category: 'files',
    valueType: 'NUMBER',
    defaultValue: 50,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 1,
    max: 100,
  },
  {
    key: 'files.types.jpeg_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.png_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.webp_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.gif_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.pdf_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.svg_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.docx_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.pptx_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.xlsx_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.types.zip_enabled',
    category: 'files',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'files.aws_s3.credential_source',
    category: 'files',
    valueType: 'STRING',
    defaultValue: 'default_chain',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['default_chain', 'stored'],
  },
  {
    key: 'files.aws_s3.access_key_id',
    category: 'files',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 256,
  },
  {
    key: 'files.aws_s3.secret_access_key',
    category: 'files',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 1024,
  },
  {
    key: 'files.aws_s3.session_token',
    category: 'files',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 8192,
  },
  {
    key: 'files.aws_s3.region',
    category: 'files',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 100,
  },
  {
    key: 'files.aws_s3.bucket',
    category: 'files',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 255,
  },
  {
    key: 'helpdesk.enabled',
    category: 'helpdesk',
    valueType: 'BOOLEAN',
    defaultValue: false,
    companyVisible: true,
    companyOverridable: true,
    companyWritable: false,
  },
  {
    key: 'trainings.enabled',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: false,
    companyVisible: true,
    companyOverridable: true,
    companyWritable: false,
  },
  {
    key: 'trainings.video.primary_provider',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'AWS_S3',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['AWS_S3', 'LOCAL'],
  },
  {
    key: 'trainings.video.local_upload_enabled',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.video.max_upload_mb',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 4096,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 1,
    max: 20480,
  },
  {
    key: 'trainings.video.aws.mediaconvert_role_arn',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 2048,
  },
  {
    key: 'trainings.video.aws.mediaconvert_queue_arn',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 2048,
  },
  {
    key: 'trainings.video.aws.cloudfront_base_url',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 2048,
  },
  {
    key: 'trainings.video.aws.cloudfront_key_pair_id',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 255,
  },
  {
    key: 'trainings.video.aws.cloudfront_private_key_base64',
    category: 'trainings',
    valueType: 'SECRET',
    defaultValue: '',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    maxLength: 16384,
  },
  {
    key: 'trainings.video.aws.upload_url_ttl_seconds',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 900,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 60,
    max: 3600,
  },
  {
    key: 'trainings.video.aws.delivery_url_ttl_seconds',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 300,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 60,
    max: 3600,
  },
  {
    key: 'trainings.player.autoplay',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.player.default_playback_rate',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: '1',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['0.75', '1', '1.25', '1.5', '2'],
  },
  {
    key: 'trainings.player.seek_seconds',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 10,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 5,
    max: 30,
    allowedValues: [5, 10, 15, 30],
  },
  {
    key: 'trainings.player.controls_auto_hide_seconds',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 2,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 1,
    max: 10,
  },
  {
    key: 'trainings.player.show_fullscreen',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.player.show_volume',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.player.show_chapters',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.player.show_speed_control',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.player.show_quality_selector',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.player.branding.enabled',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.player.branding.text',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'OdooKRD Training',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowEmpty: false,
    maxLength: 80,
  },
  {
    key: 'trainings.player.captions.default_behavior',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'prefer_learner_language',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['off', 'video_default', 'prefer_learner_language'],
  },
  {
    key: 'trainings.player.captions.font_size',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'medium',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['small', 'medium', 'large', 'xlarge'],
  },
  {
    key: 'trainings.player.captions.text_color',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'white',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['white', 'yellow'],
  },
  {
    key: 'trainings.player.captions.background',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'dark',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['none', 'light', 'medium', 'dark', 'solid'],
  },
  {
    key: 'trainings.player.captions.background_opacity',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 75,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 0,
    max: 100,
  },
  {
    key: 'trainings.player.captions.edge_style',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'soft',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['none', 'soft', 'strong'],
  },
  {
    key: 'trainings.player.captions.position',
    category: 'trainings',
    valueType: 'STRING',
    defaultValue: 'bottom',
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    allowedValues: ['bottom', 'top'],
  },
  {
    key: 'trainings.player.captions.max_width_percent',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 90,
    companyVisible: false,
    companyOverridable: false,
    companyWritable: false,
    min: 40,
    max: 100,
  },
  {
    key: 'trainings.progress.lesson_completion_percentage',
    category: 'trainings',
    valueType: 'NUMBER',
    defaultValue: 90,
    companyVisible: true,
    companyOverridable: false,
    companyWritable: false,
    min: 50,
    max: 100,
  },
  {
    key: 'trainings.quizzes.enabled',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: true,
    companyOverridable: false,
    companyWritable: false,
  },
  {
    key: 'trainings.certificates.enabled',
    category: 'trainings',
    valueType: 'BOOLEAN',
    defaultValue: true,
    companyVisible: true,
    companyOverridable: false,
    companyWritable: false,
  },
];

export const SETTINGS_BY_KEY = new Map(
  SETTINGS_REGISTRY.map((definition) => [definition.key, definition]),
);

if (SETTINGS_BY_KEY.size !== SETTINGS_REGISTRY.length) {
  throw new Error('Settings registry contains duplicate setting keys.');
}
